# Site settings
title: Arra Aravindhan

name: Arra Aravindhan

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/AA-Sourced
 
 - title: LinkedIn
   url: https://www.linkedin.com/in/arraa
 

#Any buzzword skills you want to include
skills:
 - Project Manager
 - Product Owner
 - Product Owner
 - Advanced Scrum Master
 - Cloud
 - Cyber Security
 - IAM
 - PAM
 - Customer Champion



#Work experience is required
roles:
 - title: Lead Consultant
   start: 2022
   end: Ongoing
   employer: Sourced Group
   description: Helping clinets in Telco | Financial | Private & Public Sector, migrate to cloud at Scale (AWS, Azure, GCP)
   

#Education is required
education:
 - level: Bachelor of Technology
   
   subject: Computer Science
   school: Ryerson & Seneca College

#This section is optional (as is the image link below)
#coursera:
   #profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   #courses:
    #- title: Functional Programming Principles in Scala
     # link: https://www.coursera.org/course/progfun
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      #date: September 16, 2013
    #- title: Algorithms Design and Analysis, Part 1
     # link: https://www.coursera.org/specializations/algorithms
      #optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      #date: April 28, 2014



intro: |
  Arra is an insightful, results-driven IT professional with notable success in directing a broad range of corporate IT, Cyber Security and cloud project initiatives. Extensive experience in planning, designing, analysing and implementing solutions in support of business objectives in a multi-vendor environment. Outstanding project leader with a reputation for providing excellent customer service and a tenacity to work with demanding clientele and C Level Executives.

